# LIST

### Introduction
___

In R, a list is a versatile and flexible data structure that can store elements of different data types, such as numeric, character, logical, or even other lists. Unlike vectors and arrays, which are restricted to storing elements of the same data type, lists allow for heterogeneous data, making them suitable for representing complex and structured data. A list is created using the `list()` function.

Here are some key features of lists in R:

1. **Heterogeneous Data:** Lists can contain elements of different data types within the same list. This means that you can store numeric values, character strings, logical values, or even other lists as elements of a single list.

2. **Arbitrary Length:** Lists can have an arbitrary number of elements, and each element can have a different length. This makes lists highly flexible and suitable for storing data structures of varying complexity.

3. **Indexed Access:** Elements within a list can be accessed using numeric indices or names assigned to the elements. This allows for selective retrieval and modification of list elements.

4. **Recursive Structure:** Lists can contain other lists as elements, leading to a recursive data structure. This allows for the creation of nested or hierarchical data structures, such as lists of lists or lists of data frames.

5. **Named Elements:** List elements can have names assigned to them, making it easier to reference and access specific elements within a list.

6. **Versatility:** Lists are highly versatile and can be used to represent a wide range of data structures, including collections of variables, results of statistical analyses, configurations of models, hierarchical data, and more.

7. **Operations:** Lists support various operations, including adding, removing, and modifying elements, sub-setting, merging, and combining lists, as well as applying functions to list elements.



### c function in R
___

In R, the `c()` function is used to combine values into a vector or list. The `c` stands for "concatenate" or "combine".

Here's an example of using `c()` to create a numeric vector:



In [20]:
# Create a numeric vector
my_list <- c(1, 2, 3, 4, 5)

# Print the vector
print(my_list)

[1] 1 2 3 4 5




In this example, the `c()` function is used to combine the numbers 1, 2, 3, 4, and 5 into a list, which is then assigned to the variable `my_list`. The `print()` function is then used to display the contents of `my_list`.

You can also use `c()` to combine vectors, lists, or a mix of both. The result is always a single vector or list.

### The str() function in R
___

In R, the `str()` function is used to compactly display the internal structure of an R object. This can be particularly useful for understanding the structure of complex objects, such as nested lists or data frames.

Here's an example of using `str()` with a data frame:



In [25]:
# Create a data frame
df <- data.frame(Name = c("Alice", "Bob", "Charlie"), Age = c(25, 32, 37))

# Use str() to display the structure of the data frame
str(df)

'data.frame':	3 obs. of  2 variables:
 $ Name: chr  "Alice" "Bob" "Charlie"
 $ Age : num  25 32 37




In this example, the `str()` function is used to display the structure of the `df` data frame. The output will show you the types of the columns and the first few entries in each column.

### How to Create Lists in R Programming
___

A list in R is a data structure which can hold elements of different types (like numbers, strings, vectors, or even other lists). It is similar to the concept of lists in Python. A list containing string, numbers, vectors, and logical value can created using the `list()` function as below:

In [23]:
list_data <- list("Red", "White", c(1, 2, 3), TRUE, 22.4)
print(list_data)

[[1]]
[1] "Red"

[[2]]
[1] "White"

[[3]]
[1] 1 2 3

[[4]]
[1] TRUE

[[5]]
[1] 22.4



In [26]:
# Use str() to display the structure of the list
str(list_data)

List of 5
 $ : chr "Red"
 $ : chr "White"
 $ : num [1:3] 1 2 3
 $ : logi TRUE
 $ : num 22.4


### How to Generate Lists in R as a sequence of numbers 
___

We can use a colon `:` to generate a list of numbers.

In [19]:
number <- 1:10
number 

[1]  1  2  3  4  5  6  7  8  9 10

In [27]:
# display the structure of the number
str(number)

 int [1:10] 1 2 3 4 5 6 7 8 9 10


In R, the `list()` function and the colon (`:`) operator are used for different purposes.

The `list()` function is used to create a list, which is a special type of data structure that can hold any type of objects such as vectors, matrices, data frames, even other lists, and they can all be of different types. On the other hand, the colon (`:`) operator is used to create a sequence of numbers in a vector. For example:



In [28]:
# Create a sequence of numbers
my_sequence <- 1:5
print(my_sequence)

[1] 1 2 3 4 5


In [29]:
# Display the structure of the sequence
str(my_sequence)

 int [1:5] 1 2 3 4 5




This will output a vector of numbers from 1 to 5.

So, the main difference is that `list()` is used to create lists which can hold different types of objects, while the colon (`:`) operator is used to create a sequence of numbers in a vector.

### How to Name List Elements in R Language
___

In R, you can name a list element at the time of creation or afterwards using the `names()` function. Here's how you can do it:



In [1]:
# Create a list with named elements
my_list <- list(Name = "John", Age = 25, Country = "USA")
print(my_list)

$Name
[1] "John"

$Age
[1] 25

$Country
[1] "USA"





In this example, `my_list` is a list that contains named elements. The names of the elements are "Name", "Age", and "Country".

You can also name the elements of a list after it has been created:



In [6]:
# Create a list
my_list <- list("John", 25, "USA")

# Name the elements
names(my_list) <- c("Name", "Age", "Country")

# Print the list
print(my_list)

$Name
[1] "John"

$Age
[1] 25

$Country
[1] "USA"





In this case, we first create a list and then assign names to the elements using the `names()` function. Another Example:

In [1]:
# Description: This code creates a list called 'data_list' with three elements:
# a character vector, a matrix, and another list.
# It then assigns names to each element of the list and prints the list.

data_list <- list(c("Jan", "Feb", "Mar"),
                  matrix(c(1, 2, 3, 4, -1, 9), nrow = 2),
                  list("Red", 12.3))

# Assign names to the elements of the list
names(data_list) <- c("info1", "info2", "info3")

# Print the list
print(data_list)

str(data_list)

$info1
[1] "Jan" "Feb" "Mar"

$info2
     [,1] [,2] [,3]
[1,]    1    3   -1
[2,]    2    4    9

$info3
$info3[[1]]
[1] "Red"

$info3[[2]]
[1] 12.3


List of 3
 $ info1: chr [1:3] "Jan" "Feb" "Mar"
 $ info2: num [1:2, 1:3] 1 2 3 4 -1 9
 $ info3:List of 2
  ..$ : chr "Red"
  ..$ : num 12.3


### How to Access R List Elements
___


In R, you can access elements of a list using square brackets `[ ]` notation. Lists in R can contain elements of different types, including vectors, matrices, other lists, or even functions. Here's how you can access elements of a list with some examples:

In [3]:
# Create a list
my_list2 <- list(
  numbers = c(1, 2, 3, 4, 5),
  characters = c("a", "b", "c"),
  matrix = matrix(1:9, nrow = 3),
  sublist = list(x = 10, y = 20)
)

print(my_list2)

$numbers
[1] 1 2 3 4 5

$characters
[1] "a" "b" "c"

$matrix
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$sublist
$sublist$x
[1] 10

$sublist$y
[1] 20




In [4]:
# Display the structure of the list
str(my_list2)

List of 4
 $ numbers   : num [1:5] 1 2 3 4 5
 $ characters: chr [1:3] "a" "b" "c"
 $ matrix    : int [1:3, 1:3] 1 2 3 4 5 6 7 8 9
 $ sublist   :List of 2
  ..$ x: num 10
  ..$ y: num 20


An alternative to [], which is used often while accessing content of a list is the `$` operator. They are both the same, except that $ can do partial matching on tags.

* **Accessing by Name:** 
____

You can access elements by their names if they are named.

In [10]:
# Accessing elements by name
my_list2$numbers
my_list2$characters

[1] 1 2 3 4 5

[1] "a" "b" "c"

In [11]:
# Accessing elements from previous list
data_list$info1
data_list$info3

[1] "Jan" "Feb" "Mar"

[[1]]
[1] "Red"

[[2]]
[1] 12.3

In [ ]:
# using $ can do partial matching on tags.

x <- list(name = "John", age = 19, speaks = c("English", "French"))

# access element by exact matching using $
x$name

# access element by partial matching using $
x$age

# access element by partial matching using $
x$speaks

# create a list with similar tags
y <- list(n = "Alice", a = 25, s = c("Spanish", "Italian"))

# access element by partial matching using $
y$n

# access element by partial matching using $
y$a

# access element by partial matching using $
y$s

[1] "John"

[1] 19

[1] "English" "French"

[1] "Alice"

[1] 25

[1] "Spanish" "Italian"

* **Using Square Brackets `[ ]` to access a list element:** 
___
In R, the square brackets [ ] and double square brackets [[ ]] are used to subset or extract elements from lists. While they may appear similar, they have different behaviors:

Square Brackets [ ]:  

- When you use square brackets [ ], you obtain a sublist containing the specified elements (conetnt).
- If you provide multiple INDICES or NAMES, you will get a list containing the specified elements.
- Square brackets can return a sublist or a single element wrapped in a list.

Double Square Brackets [[ ]]:  
- When you use double square brackets [[ ]], you get the actual content of the specified element.
- It's used to directly access a single element from the list.
- Double square brackets will always return the element itself, not wrapped in a list.

consider the following example 

In [ ]:
my_list <- list(
  numbers = c(1, 2, 3),
  letters = c("a", "b", "c"),
  matrix = matrix(1:4, nrow = 2)
)


In [ ]:
# Using [ ]: Accessing elements by position
# This [ ] shows the content and name of the list
sublist <- my_list[c("numbers", "letters")]
print(sublist)

$numbers
[1] 1 2 3

$letters
[1] "a" "b" "c"



In [ ]:
# Using [[ ]]: Accessing elements by position
# This [[ ]] shows the content of the list
numbers_vector <- my_list[["numbers"]]
print(numbers_vector)

numbers_vector <- my_list[["letters"]]
print(numbers_vector)

[1] 1 2 3
[1] "a" "b" "c"


In [ ]:
# Accessing elements using square brackets
my_list["numbers"]  # Accessing 'numbers' element
my_list[[1]]  # Equivalent to accessing 'numbers' element


$numbers
[1] 1 2 3 4 5

[1] 1 2 3 4 5

Summary:
- Use [ ] when you want to extract a sublist or multiple elements, which may result in a list.
- Use [[ ]] when you want to directly access a single element from the list, which will return the element itself, not wrapped in a list.

* How to Manipulate List elements in R Programming
____

We can add, delete and update list elements as shown below. We can add and delete elements only at the end of a list. But we can update any element.

In [ ]:
data_list <- list(
  c("Feb", "Mar", "Apr"),
  matrix(c(3, 9, 5, 1, -2, 8), nrow = 2),
  list("green", 12.3)
)

# Give names to the elements of the list
names(data_list) <- c("Monat", "Matrix", "Misc")
print(data_list)


$Monat
[1] "Feb" "Mar" "Apr"

$Matrix
     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8

$Misc
$Misc[[1]]
[1] "green"

$Misc[[2]]
[1] 12.3




In [ ]:
# Add an element at the end of the list.
data_list[4] <- "New element"
print(data_list)

$Monat
[1] "Feb" "Mar" "Apr"

$Matrix
     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8

$Misc
$Misc[[1]]
[1] "green"

$Misc[[2]]
[1] 12.3


[[4]]
[1] "New element"



In [ ]:
# Remove the an element.
data_list <- data_list[-2]
print(data_list)

$Monat
[1] "Feb" "Mar" "Apr"

$Misc
$Misc[[1]]
[1] "green"

$Misc[[2]]
[1] 12.3




In [ ]:
# Update the 3rd Element.
data_list[[3]] <- list("Blue", 15.6)
print(data_list)

$Monat
[1] "Feb" "Mar" "Apr"

$Misc
$Misc[[1]]
[1] "green"

$Misc[[2]]
[1] 12.3


[[3]]
[[3]][[1]]
[1] "Blue"

[[3]][[2]]
[1] 15.6




In [42]:
# We can delete a component by assigning NULL to it.
x <- list(name = "Clair", age = 19, speaks = c("English", "French"))

# remove an element from the list using double brackets [[]]
x[["age"]] <- NULL

# print the structure of the updated list
str(x)

List of 2
 $ name  : chr "Clair"
 $ speaks: chr [1:2] "English" "French"


### How to Merge Lists in R Programming language
___

We can merge many lists into one list by placing all the lists element inside one list() function. In R, you can merge lists using the c() function. Here's an example:

In [8]:
# Define two lists
list1 <- list("a", "b", "c")
list2 <- list("d", "e", "f")

# Merge the lists
merged_list <- c(list1, list2)

# Print the merged list
print(merged_list)

[[1]]
[1] "a"

[[2]]
[1] "b"

[[3]]
[1] "c"

[[4]]
[1] "d"

[[5]]
[1] "e"

[[6]]
[1] "f"



In this example, list1 and list2 are merged into merged_list using the c() function. The print() function is then used to display the contents of merged_list.

In [7]:
# Define a list with numeric elements
num_list <- list(1, 2, 3, 4, 5)
day_list <- list("Mon", "Tue", "Wed", "Thurs", "Fri")

# Merge the two lists
merge_list <- c(num_list, day_list)

# Print the merged list
merge_list

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] 5

[[6]]
[1] "Mon"

[[7]]
[1] "Tue"

[[8]]
[1] "Wed"

[[9]]
[1] "Thurs"

[[10]]
[1] "Fri"

### How to Convert R List to Vector
___

A list can be converted to a vector so that the elements of the vector can be used for further manipulation. All the arithmetic operations on vectors can be applied after the list is converted into vector. To do this conversion, we can use the `unlist()` function. It takes the list as input and produces a vector.

In [12]:
# Create a list Example 1
int_list <- list(1:5)
print(int_list)

# Create a list Example 2
int_list2 <- list(10:14)
print(int_list2)

# checking data type 
typeof(int_list)
typeof(int_list2)

[[1]]
[1] 1 2 3 4 5

[[1]]
[1] 10 11 12 13 14



[1] "list"

[1] "list"

In [15]:
# Convert the lists to vectors.
vec1 <- unlist(int_list)
vec2 <- unlist(int_list2)
print(vec1)
print(vec2)

# checking data type
class(vec1)
typeof(vec2)


[1] 1 2 3 4 5
[1] 10 11 12 13 14


[1] "integer"

[1] "integer"

In [17]:
# Now add the vectors.
sum_vec <- vec1 + vec2
print(sum_vec)


[1] 11 13 15 17 19


### Summary 
___

We have studied the R list in the above-mentioned information. We all are aware, that lists are the object which contains elements of different types like strings, numbers, and vectors. Thus, it is necessary to learn how to apply different operations on list elements.