# ARRAY

### Introduction
____

In R programming, arrays are a fundamental data structure used to store collections of elements that can have more than two dimensions. This allows you to organize your data in a more structured and efficient way compared to one-dimensional vectors or two-dimensional matrices. It is created by using `array()` function.

Key Characteristics:

* Dimensions: Arrays can have one or more dimensions. A one-dimensional array is essentially a vector, but R treats them slightly differently in some functions. Two-dimensional arrays are equivalent to matrices, which are commonly used in R. Three-dimensional arrays (or higher) provide additional layers for organizing your data.

* Data Type Consistency: All elements within an array must be of the same data type. This ensures uniformity and simplifies operations on the array.

This is array syntax: 

```R
Array_name <- array(c(data1,data2) dim = c(row_size, column_size, matrices), dimnames = list(row_names, column_names, matrix_names)))

```

Arguments definition: 

- `c` This call for a creation of a vector of numbers 

- `data`: Data is an input vector that is given to the array.

- `dim`: This is the deimension of the argument as a vector of integers. 

- `row_size` : row_Size describes the number of row elements that an array can store.

- `column_size` : Number of column elements that can be stored in an array.

- `matrices` : Array in R consists of multi-dimensional matrices.

- `dimnames` : Used to change the default names of rows and columns to the user’s preference.


### How to Create Array in R
___

Now, we will create an R array of two 3×3 matrices each with 3 rows and 3 columns.

- first # Create two vectors of different lengths.
- Take these vectors as input to the array.

In [28]:
# Create two vectors of different lengths.
vector1 <- c(2, 9, 3)
vector2 <- c(10, 16, 17, 13, 11, 15)

In [29]:
# Take these vectors as input to the array.
result <- array(c(vector1, vector2), dim = c(3, 3, 2))
print(result)

, , 1

     [,1] [,2] [,3]
[1,]    2   10   13
[2,]    9   16   11
[3,]    3   17   15

, , 2

     [,1] [,2] [,3]
[1,]    2   10   13
[2,]    9   16   11
[3,]    3   17   15



This R script creates two vectors of different lengths, combines them, and then reshapes the combined data into a multidimensional array.

Here's a breakdown of the script:

- Two vectors, `vector1` and `vector2`, are created using the `c()` function. `vector1` contains three elements: 2, 9, and 3. `vector2` contains six elements: 10, 16, 17, 13, 11, and 15.

- The `c()` function is used again to combine `vector1` and `vector2` into a single vector. This combined vector contains all the elements of `vector1` followed by all the elements of `vector2`.

- The `array()` function is used to create an array from the combined vector. The `dim` argument is set to `c(3, 3, 2)`, which specifies the dimensions of the array. This creates a 3D array with 3 rows, 3 columns, and 2 slices (or layers). 

- The `print()` function is used to display the `result` array. This will print a 3D array where the first slice contains the first 9 elements of the combined vector (filled by column), and the second slice contains the remaining elements.

In summary, this script demonstrates how to create a multidimensional array in R from vectors of different lengths.

In [66]:
# An array with one dimension with values ranging from 1 to 24
thisarray <- c(1:24)
thisarray

# An array with more than one dimension
multiarray <- array(thisarray, dim = c(4, 3, 2))
print(multiarray)

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24



### Naming Columns And Rows
___

We can give names to the rows, columns, and matrices in the array by using the dimnames parameter.

In [30]:
# # Create two vectors of different lengths.
vector1 <- c(2, 9, 6)
vector2 <- c(10, 15, 13, 16, 11, 12)
column_names <- c("COL1", "COL2", "COL3")
row_names <- c("ROW1", "ROW2", "ROW3")
matrix_names <- c("Matrix1", "Matrix2")

In [31]:
# Take these vectors as input to the array.
result <- array(
  c(vector1, vector2), dim = c(3, 3, 2),
  dimnames = list(row_names, column_names, matrix_names)
)


print(result)


, , Matrix1

     COL1 COL2 COL3
ROW1    2   10   16
ROW2    9   15   11
ROW3    6   13   12

, , Matrix2

     COL1 COL2 COL3
ROW1    2   10   16
ROW2    9   15   11
ROW3    6   13   12



This R script creates a multidimensional array from two vectors and assigns names to the dimensions of the array.

Here's a breakdown of the script:

- The `c()` function is used to combine `vector1` and `vector2` into a single vector. This combined vector is the data that will be used to create the array.

- The `array()` function is used to create an array from the combined vector. The `dim` argument is set to `c(3, 3, 2)`, which specifies the dimensions of the array. This creates a 3D array with 3 rows, 3 columns, and 2 slices (or layers).

- The `dimnames` argument of the `array()` function is used to assign names to the dimensions of the array. The `list()` function is used to create a list of three vectors: `row_names`, `column_names`, and `matrix_names`. These vectors provide the names for the rows, columns, and slices of the array, respectively.

In summary, this script demonstrates how to create a named multidimensional array in R from vectors of different lengths. The names of the dimensions can be used to make the data in the array easier to understand and work with.

### Accessing R Array Elements
___

You can access the array elements by referring to the index position. You can use the `[]` brackets to access the desired elements from an array:

In [72]:
# An array with one dimension with values ranging from 1 to 24
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(8, 3, 1))
print(multiarray)

multiarray[6, 3, 1]

, , 1

     [,1] [,2] [,3]
[1,]    1    9   17
[2,]    2   10   18
[3,]    3   11   19
[4,]    4   12   20
[5,]    5   13   21
[6,]    6   14   22
[7,]    7   15   23
[8,]    8   16   24



[1] 22

In [53]:
# # We will create two vectors of different lengths.
info1 <- c(2, 9, 6)
info2 <- c(10, 15, 13, 7, 0, 3)
column_names <- c("COL1", "COL2", "COL3")
row_names <- c("ROW1", "ROW2", "ROW3")
matrix_names <- c("Matrix1", "Matrix2")

In [52]:
# # Now, we will take these vectors as input to the array.
result <- array(
  c(info1, info2), dim = c(3, 3, 2),
  dimnames = list(row_names, column_names, matrix_names)
)


print(result)

, , Matrix1

     COL1 COL2 COL3
ROW1    2   10    7
ROW2    9   15    0
ROW3    6   13    3

, , Matrix2

     COL1 COL2 COL3
ROW1    2   10    7
ROW2    9   15    0
ROW3    6   13    3



In [54]:
#  Print the element in the 1st row and 3rd column of the 1st matrix.
# dim = (row_Size, column_Size, matrices, dimnames)

print(result[1, 3, 1])

[1] 7


In [55]:
# # Print the 2nd Matrix.
# dim = (row_Size, column_Size, matrices, dimnames)

print(result[, , 2])

     COL1 COL2 COL3
ROW1    2   10    7
ROW2    9   15    0
ROW3    6   13    3


In [56]:
# # Print the 2nd row of the 1st matrix.
# dim = (row_Size, column_Size, matrices, dimnames)
print(result[2, , 1])

COL1 COL2 COL3 
   9   15    0 


In [58]:
# # Print the 3rd column of the 2nd matrix.
# dim = (row_Size, column_Size, matrices, dimnames)
print(result[, 3, 2])

ROW1 ROW2 ROW3 
   7    0    3 


In [38]:
# # Print the 2nd row of the 2nd matrix.
print(result[2, , 2])

COL1 COL2 COL3 
   9   15    0 


### Check if an Item Exists
___

To find out if a specified item is present in an array, use the `%in% `operator: it returns a boolean value.

- TRUE - if specified element is present in the matrix
- FALSE - if specified element is not present in the matrix

In [73]:
# Check if the value "2" is present in the array:
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

2 %in% multiarray

[1] TRUE

### Array Length
___

Use the `length()` function to find the dimension of an array:

In [76]:
# create a two 2 by 3 matrix
array1 <- array(c(1:12), dim = c(2, 3, 2))

# find total elements in array1 using length()
cat("Total Elements:", length(array1))

Total Elements: 12

### Amount of Rows and Columns
___

Use the `dim()` function to find the amount of rows and columns in an array:

In [74]:
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

dim(multiarray)

[1] 4 3 2

### Manipulating R Array Elements
___

As the array is made up matrices in multiple dimensions, the operations on elements of an array are carried out by accessing elements of the matrices.

In [39]:
# Create two vectors of different lengths.
vector1 <- c(1, 2, 3)
vector2 <- c(3, 4, 5, 6, 7, 8)

In [40]:
# Take these vectors as input to the array.
array1 <- array(c(vector1, vector2), dim = c(3, 3, 2))

In [41]:
# Create two vectors of different lengths.
vector3 <- c(3, 2, 1)
vector4 <- c(8, 7, 6, 5, 4, 3)
array2 <- array(c(vector1, vector2), dim = c(3, 3, 2))

In [60]:
# create matrices from these arrays.
matrix1 <- array1[, , 1] # assessing the first matrix
matrix2 <- array2[, , 2] # assessing the second matrix

print(matrix1)
print(matrix2)

     [,1] [,2] [,3]
[1,]    1    3    6
[2,]    2    4    7
[3,]    3    5    8
     [,1] [,2] [,3]
[1,]    1    3    6
[2,]    2    4    7
[3,]    3    5    8


In [61]:
# Add the matrices.
result <- matrix1 + matrix2

print(result)

     [,1] [,2] [,3]
[1,]    2    6   12
[2,]    4    8   14
[3,]    6   10   16


### Calculations across R Array Elements
___

We will be using the `apply( )`function for calculations in an array in R.

The `apply()` function in R is a powerful tool for working with matrices and data frames. Here's a breakdown of its functionality and an example:

What is apply() in R?

* It's a function that iterates over rows or columns of a matrix or data frame and applies a specified function to each row or column.

* This allows you to perform calculations or transformations on your data in a concise and efficient way, avoiding explicit loops.

The Sytnax: 

```r
apply(X, margin, fun)
```

Key Arguments:

- X (data): The matrix or data frame you want to apply the function to.

- MARGIN (dimension): An integer specifying which dimension (rows or columns) to apply the function over.

     * MARGIN = 1: Applies the function to each row (default).
     * MARGIN = 2: Applies the function to each column.
     
- FUN (function): The function you want to apply to each row or column. This can be a built-in R function (like sum, mean, max) or a user-defined function.


In [44]:
# # We will create two vectors of different lengths.
vector1 <- c(1, 2, 3)
vector2 <- c(3, 4, 5, 6, 7, 8)

In [45]:
# Now, we will take these vectors as input to the array.
array1 <- array(c(vector1, vector2), dim = c(3, 3, 2))
print(array1)

, , 1

     [,1] [,2] [,3]
[1,]    1    3    6
[2,]    2    4    7
[3,]    3    5    8

, , 2

     [,1] [,2] [,3]
[1,]    1    3    6
[2,]    2    4    7
[3,]    3    5    8



In [46]:
# Use apply to calculate the sum of the rows across all the matrices.
result1 <- apply(array1, c(1), sum)
print(result1)

[1] 20 26 32


In [47]:
# Use apply to calculate the sum of the column across all the matrices.
result2 <- apply(array1, c(2), sum)
print(result2)

[1] 12 24 42


In [48]:
# Use apply to calculate the sum of the matrices across.
# all the rows and columns.
result3 <- apply(array1, c(1, 2), sum)
print(result3)


     [,1] [,2] [,3]
[1,]    2    6   12
[2,]    4    8   14
[3,]    6   10   16


In [49]:
# Use the apply to calculate the mean of the column.
result4 <- apply(array1, c(2), mean)
print(result4)

[1] 2 4 7


In [50]:
# use the apply to calculate the mean of the column and row 
result5 <- apply(array1, c(1, 2), mean)
print(result5)

     [,1] [,2] [,3]
[1,]    1    3    6
[2,]    2    4    7
[3,]    3    5    8


### Key Differences Between Matrix and Array
____

In R, both arrays and matrices are used to store data in a structured format, but they have some key differences in terms of their structure and usage. Here are the main differences:

#### Matrix
- **Definition:** A matrix is a two-dimensional array, meaning it has rows and columns.
- **Dimensions:** Always has exactly two dimensions.
- **Creation:** Created using the `matrix()` function.
- **Usage:** Primarily used for mathematical computations and linear algebra operations.
- **Example:**
  ```r
  # Creating a matrix
  mat <- matrix(1:9, nrow = 3, ncol = 3)
  print(mat)
  ```

#### Array
- **Definition:** An array is a multi-dimensional data structure that can have more than two dimensions.
- **Dimensions:** Can have two or more dimensions.
- **Creation:** Created using the `array()` function.
- **Usage:** Used for more complex data structures that require more than two dimensions.
- **Example:**
  ```r
  # Creating a 3-dimensional array
  arr <- array(1:27, dim = c(3, 3, 3))
  print(arr)
  ```

#### Key Differences
1. **Dimensionality:**
   - **Matrix:** Always 2D (rows and columns).
   - **Array:** Can be 2D, 3D, or higher.

2. **Creation Functions:**
   - **Matrix:** Created using `matrix()`.
   - **Array:** Created using `array()`.

3. **Usage Context:**
   - **Matrix:** Commonly used for linear algebra operations, such as matrix multiplication, inversion, etc.
   - **Array:** Used when data needs to be stored in more than two dimensions, such as in multi-dimensional data analysis.

#### Example Code
Here is an example to illustrate the creation and usage of both a matrix and an array in R:



In [5]:
# Creating a matrix
mat <- matrix(1:9, nrow = 3, ncol = 3)
print("Matrix:")
print(mat)


[1] "Matrix:"
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [8]:
# Creating a 3-dimensional array
arr <- array(1:9, dim = c(3, 3, 3))
print("Array:")
print(arr)

[1] "Array:"
, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 3

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9





### Output




In summary, matrices are a special case of arrays with exactly two dimensions, while arrays can have multiple dimensions and are used for more complex data structures.