# MATRIX

### Introduction 
___

In R, a matrix is a fundamental data structure that represents a two-dimensional rectangular arrangement of elements. It's similar to a spreadsheet with rows and columns, where each element at a specific location (row and column) is called an entry. Matrices are often used for storing and manipulating numerical data, but they can also hold characters or logical values.

### How to Create Matrix in R?
___


There are 3 primary ways to create matrices in R:

1. **Using the matrix() function:**
___

The syntax is thus: 

``` R
my_matrix <- matrix(data, nrow, ncol, byrow = TRUE, dimnames = list(row_names, col_names))

```

This is the most common approach. The `matrix()` function takes several arguments:

- data:This is the input vector. This can also include a list or an expression.

- nrow: The number of rows in the matrix (required).

- ncol: The number of columns in the matrix (required).

- byrow (optional): a logical value indicating whether the matrix should be filled by rows (TRUE) or by columns (FALSE). The default is FALSE.

- dimnames (optional): A list to assign names to the rows and columns.

> Note that the `dimnames` have a `list` before the specifying of the row_names, and col_name


In [5]:
# Create a matrix filled column-wise
mat1 <- matrix(1:12, nrow = 3, ncol = 4)
print(mat1)


     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12


In [2]:
mat8 <- matrix(1:12, nrow = 3, ncol = 4, byrow = TRUE, dimnames = list(c("row1", "row2", "row3"), c("col1", "col2", "col3", "col4")))
print(mat8)

     col1 col2 col3 col4
row1    1    2    3    4
row2    5    6    7    8
row3    9   10   11   12


In [4]:
mat9 <- matrix(1:12, nrow = 3, ncol = 4, byrow = FALSE, dimnames = list(c("row1", "row2", "row3"), c("col1", "col2", "col3", "col4")))
print(mat9)

     col1 col2 col3 col4
row1    1    4    7   10
row2    2    5    8   11
row3    3    6    9   12


2. **Using cbind() and rbind():**
___

These functions are useful for combining vectors or matrices into a larger matrix.

- `cbind()`: Combines vectors or matrices side-by-side to create columns.

- `rbind()`: Combines vectors or matrices on top of each other to create rows.

Example (creating the same matrix as before):

In [21]:
column1 <- c(1, 2, 3)
column2 <- c(4, 5, 6)
column3 <- c(7, 8, 9)
my_matrix <- cbind(column1, column2, column3)
print(my_matrix)


     column1 column2 column3
[1,]       1       4       7
[2,]       2       5       8
[3,]       3       6       9


In [22]:
# Another way to create a column bind matrix
a <- cbind(c(1, 2, 3), c(4, 5, 6))
print(a)


     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6


In [23]:
# create a row bind matrix
b <- rbind(c(1, 2, 3), c(4, 5, 6))

print(b)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6


**3. Create Matrix Using dim()**
___  
Finally, you can also create a matrix from a vector by setting its dimension using dim().


In [3]:
x <- c(1, 2, 3, 4, 5, 6)

dim(x) <- c(2, 3)
print(x)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [25]:
news = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
dim(news) <- c(3,4)
print(news)

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12


> Note: We can check if a variable is a matrix or not with the class() function. For example, in the above matrix, we can check that as:

In [26]:
class(news)
class(x)
class(b)

[1] "matrix" "array"

[1] "matrix" "array"

[1] "matrix" "array"

### Creating R matrix based on the variations in the attributes
___

In [27]:
# Creating R matrix through the arrangement of elements sequentially by row
arrang_row <- matrix(c(1:12), nrow = 4, byrow = TRUE)

print(arrang_row)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[4,]   10   11   12


This R code snippet demonstrates how to create a matrix with elements arranged sequentially by row.

First, the `matrix()` function is used to create a matrix. This function takes several arguments, including the data to be used to fill the matrix, the number of rows, and a logical argument `byrow` that determines how the matrix is filled.

In this case, the data is a sequence of numbers from 1 to 12, created using the `c()` function and the `:` operator. The `c()` function in R is used to create a vector. Here, `c(1:12)` creates a vector of numbers from 1 to 12.

The `nrow = 4` argument specifies that the matrix should have 4 rows. The number of columns is inferred from the length of the data and the number of rows. Since there are 12 elements and 4 rows, the matrix will have 3 columns.

The `byrow = TRUE` argument specifies that the matrix should be filled by rows. This means that the elements are arranged sequentially by row, rather than by column (which is the default). So, the first row will contain the first three numbers (1, 2, 3), the second row will contain the next three numbers (4, 5, 6), and so on.

The resulting matrix is assigned to the variable `arrang_row`.

Finally, the `print()` function is used to display the `arrang_row` matrix. The output of this code will be a 4x3 matrix where the elements are arranged sequentially by row.

In [28]:
# Creating R matrix through the arrangement of elements sequentially by column
arrang_col <- matrix(c(1:12), nrow = 4, byrow = FALSE)

print(arrang_col)

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12


In [4]:
# Defining names of columns and rows in a matrix
rows_name <- c("info1", "info2", "info3", "info4")  # Names of the rows in the matrix
cols_name <- c("column1", "column2", "column3") # Names of the columns in the matrix

# Creating a matrix with specified values, row names, and column names
info <- matrix(c(1:12), nrow = 4, byrow = TRUE, dimnames = list(rows_name, cols_name)) # Note the use of list before those row and col names. 

print(info)

      column1 column2 column3
info1       1       2       3
info2       4       5       6
info3       7       8       9
info4      10      11      12


This R code snippet demonstrates how to create a matrix with specified values, row names, and column names.

First, it defines the names of the rows and columns of the matrix. The `c()` function is used to create vectors of strings that represent the names of the rows and columns. These vectors are assigned to the variables `rows` and `cols`, respectively.

Next, the `matrix()` function is used to create the matrix. The first argument to this function is a vector of numbers from 1 to 12, created using the `c()` function and the `:` operator. The `nrow = 4` argument specifies that the matrix should have 4 rows. The `byrow = TRUE` argument indicates that the matrix should be filled by rows, meaning that the elements are arranged sequentially by row, rather than by column.

The `dimnames = list(rows, cols)` argument assigns the names of the rows and columns to the matrix. The `list()` function is used to create a list of the `rows` and `cols` vectors. The first element of the list is used as the row names, and the second element is used as the column names.

The resulting matrix is assigned to the variable `mat`.

Finally, the `print()` function is used to display the `mat` matrix. The output of this code will be a 4x3 matrix with the specified row and column names, and the elements arranged sequentially by row.

In [14]:
location_name  <- c("Location1", "Location2", "Location3", "Location4")
class_name <- c("Class A", "Class B", "Class C", "Class D", "Class E")

ma6 <- matrix(c(1:20), nrow = 4, ncol = 5, dimnames = list(location_name, class_name))
ma6

Class A Class B Class C Class D Class E
Location1 1       5        9      13      17     
Location2 2       6       10      14      18     
Location3 3       7       11      15      19     
Location4 4       8       12      16      20

### How to Access Elements of Matrix in R?
___

You can access individual elements of a matrix using square brackets `[ ]`. To specify a row and column, use their respective indices within the brackets:

```R
value <- my_matrix_name[row_index, col_index]
```
- If any field inside the bracket is left blank, it selects all.

- We can use negative integers to specify rows or columns to be excluded.


In [21]:
# creating a matrix with specified values, row names, and column names
rows_name <- c("info1", "info2", "info3", "info4")  
cols_name <- c("column1", "column2", "column3")

info <- matrix(c(1:12), nrow = 4, ncol = 3, byrow = TRUE, dimnames = list(rows_name, cols_name))
info

# Accessing the element at the first row and first column
element_at_row_1_col_1 <- info[1, 1]
print(element_at_row_1_col_1)
class(element_at_row_1_col_1)
# output:1

column1 column2 column3
info1  1       2       3     
info2  4       5       6     
info3  7       8       9     
info4 10      11      12

[1] 1


[1] "integer"

In [22]:
# creating a matrix with specified values, row names, and column names
rows_name <- c("info1", "info2", "info3", "info4")  # Names of the rows in the matrix
cols_name <- c("column1", "column2", "column3")

info <- matrix(c(1:12), nrow = 4, ncol = 3, byrow = TRUE, dimnames = list(rows_name, cols_name))
info

# Accessing the element at the second row and third column
element_at_row_2_col_3 <- info[2, 3]
print(element_at_row_2_col_3)
class(element_at_row_2_col_3)
# output:6


column1 column2 column3
info1  1       2       3     
info2  4       5       6     
info3  7       8       9     
info4 10      11      12

[1] 6


[1] "integer"

In [19]:
# creating a matrix with specified values, row names, and column names
rows_name <- c("info1", "info2", "info3", "info4")  # Names of the rows in the matrix
cols_name <- c("column1", "column2", "column3")

info <- matrix(c(1:12), nrow = 4, ncol = 3, byrow = TRUE, dimnames = list(rows_name, cols_name))
info

# Accessing the element at the third row and second column
element_at_row_3_col_2 <- info[3, 2]
print(element_at_row_3_col_2)
class(element_at_row_3_col_2)
# output:8

column1 column2 column3
info1  1       2       3     
info2  4       5       6     
info3  7       8       9     
info4 10      11      12

[1] 8


[1] "integer"

In [20]:
# creating a matrix with specified values, row names, and column names
rows_name <- c("info1", "info2", "info3", "info4")  # Names of the rows in the matrix
cols_name <- c("column1", "column2", "column3")

info <- matrix(c(1:12), nrow = 4, ncol = 3, byrow = TRUE, dimnames = list(rows_name, cols_name))
info

# Accessing the element at the fourth row and second column
element_at_row_4_col_2 <- info[4, 2]
print(element_at_row_4_col_2)
class(element_at_row_4_col_2)
# output:11

column1 column2 column3
info1  1       2       3     
info2  4       5       6     
info3  7       8       9     
info4 10      11      12

[1] 11


[1] "integer"

In [24]:
# creating a matrix with specified values, row names, and column names
rows_name <- c("info1", "info2", "info3", "info4")  # Names of the rows in the matrix
cols_name <- c("column1", "column2", "column3")

info <- matrix(c(1:12), nrow = 4, ncol = 3, byrow = TRUE, dimnames = list(rows_name, cols_name))
info

# accessing the second row of the matrix
row_2 <- info[2, ]
print(row_2)
class(row_2)


column1 column2 column3
info1  1       2       3     
info2  4       5       6     
info3  7       8       9     
info4 10      11      12

column1 column2 column3 
      4       5       6 


[1] "integer"

In [25]:
# creating a matrix with specified values, row names, and column names
rows_name <- c("info1", "info2", "info3", "info4")  # Names of the rows in the matrix
cols_name <- c("column1", "column2", "column3")

info <- matrix(c(1:12), nrow = 4, ncol = 3, byrow = TRUE, dimnames = list(rows_name, cols_name))
info


# accessing the third column of the matrix
col_3 <- info[, 3]
print(col_3)
class(col_3)


column1 column2 column3
info1  1       2       3     
info2  4       5       6     
info3  7       8       9     
info4 10      11      12

info1 info2 info3 info4 
    3     6     9    12 


[1] "integer"

One thing to notice here is that, if the matrix returned after indexing is a row matrix or column matrix, the result is given as a vector instead as matrix. This can be corrected by by using the argument `drop` = FALSE while indexing. If we do:

In [29]:
rows_name <- c("info1", "info2", "info3", "info4")  # Names of the rows in the matrix
cols_name <- c("column1", "column2", "column3")

info <- matrix(c(1:12), nrow = 4, ncol = 3, byrow = TRUE, dimnames = list(rows_name, cols_name))
info

# Accessing the element at the first row and first column
element_at_row_1_col_1 <- info[1, 1, drop = FALSE]
print(element_at_row_1_col_1)
class(element_at_row_1_col_1)
# output:1

# Accessing the element at the second row and third column
element_at_row_2_col_3 <- info[2, 3, drop = FALSE]
print(element_at_row_2_col_3)
class(element_at_row_2_col_3)
# output:6

# Accessing the element at the third row and second column
element_at_row_3_col_2 <- info[3, 2, drop = FALSE]
print(element_at_row_3_col_2)
class(element_at_row_3_col_2)
# output:8

# Accessing the element at the fourth row and second column
element_at_row_4_col_2 <- info[4, 2, drop = FALSE]
print(element_at_row_4_col_2)
class(element_at_row_4_col_2)
# output:11

# accessing the second row of the matrix
row_2 <- info[2,, drop = FALSE]
print(row_2)
class(row_2)
# output:column1 column2 column3
# info2       4       5       6

# accessing the third column of the matrix
col_3 <- info[, 3, drop = FALSE]
print(col_3)
class(col_3)
# output:info1 info2 info3 info4
#     3     6     9    12

column1 column2 column3
info1  1       2       3     
info2  4       5       6     
info3  7       8       9     
info4 10      11      12

      column1
info1       1


[1] "matrix" "array"

      column3
info2       6


[1] "matrix" "array"

      column2
info3       8


[1] "matrix" "array"

      column2
info4      11


[1] "matrix" "array"

      column1 column2 column3
info2       4       5       6


[1] "matrix" "array"

      column3
info1       3
info2       6
info3       9
info4      12


[1] "matrix" "array"

### How to Modify Matrix in R?
___

In order to modify our matrix ‘mat’ in R, there are several methods



**1. Assign a Single Element**  
The first method is to assign a single element to the position of the R matrix that will modify the original value.

The basic syntax for is `my_matrix_name`[row,column] <- y, where the row and columnm are follow respectively. And, y is the value that we assign to modify our matrix.

In [61]:
# creating a matrix with specified values, row names, and column names
info <- matrix(c(1:12), nrow = 4, byrow = TRUE, dimnames = list(rows, cols))

# assigning a new value to the element at the first row and first column
info[1, 1] <- 100
print(info)

      column1 column2 column3
info1     100       2       3
info2       4       5       6
info3       7       8       9
info4      10      11      12


In [62]:
# assigning a new value to the element at the second row and third column
info[2, 3] <- 200
print(info)

      column1 column2 column3
info1     100       2       3
info2       4       5     200
info3       7       8       9
info4      10      11      12


**2. Use of Relation Operators**  
Another method of modifying is with the use of relational operators like >, <, ==. This is looking for a specific element to be replace with the operator function of >, <, ==.

In [65]:
# creating a matrix with specified values, row names, and column names
info <- matrix(c(1:12), nrow = 4, byrow = TRUE, dimnames = list(rows, cols))

# Replacing all occurrences of 4 in the matrix with 108
info[info == 4] <- 108
print(info)

      column1 column2 column3
info1       1       2       3
info2     108       5       6
info3       7       8       9
info4      10      11      12


In [66]:

#Replacing all occurrences of 8 in the matrix with 208
info[info == 8] <- 208
print(info)

      column1 column2 column3
info1       1       2       3
info2     108       5       6
info3       7     208       9
info4      10      11      12


In [67]:
# Replacing all occurrences that are greater than 5 in the matrix with 145
info[info < 5] <- 145
print(info)

      column1 column2 column3
info1     145     145     145
info2     108       5       6
info3       7     208       9
info4      10      11      12


**3. Addition of Rows and Columns**   
Another method of modifying an R matrix is through the addition of rows and columns using the `rbind()` and `cbind()` function respectively. For this, we create a new matrix ‘new_info with 5th rows and 4th columns:

The `rownames` and `colnames` are use to rename the newly created row and column. 

In [80]:
# creating a matrix with specified values, row names, and column names
info <- matrix(c(1:12), nrow = 4, byrow = TRUE, dimnames = list(rows, cols))

# create a 5th row with values 13, 14, 15
info1 <- rbind(info, c(13, 14, 15))

# name the new row
rownames(info1)[5] <- "info5"

# print the updated matrix
print(info1)


      column1 column2 column3
info1       1       2       3
info2       4       5       6
info3       7       8       9
info4      10      11      12
info5      13      14      15


In [96]:
# creating a matrix with specified values, row names, and column names
info <- matrix(c(1:12), nrow = 4, byrow = TRUE, dimnames = list(rows, cols))

# create a 4th column with values 12, 24, 36, 48
info2 <- cbind(info, c(12, 24, 35, 48))

# name the new column
colnames(info2)[4] <- "column4"

# print the updated matrix
print(info2)

      column1 column2 column3 column4
info1       1       2       3      12
info2       4       5       6      24
info3       7       8       9      35
info4      10      11      12      48


### Changing the dimension of the matrix 
___

To change the dimensions of a matrix in R, you can use the `dim()` function. This function allows you to set the number of rows and columns of the matrix. It returns a vector of length (row, colum) indicating the number of `rows` and `columns` for a matrix, or more generally, the length in each dimension for an array.

Matrix is similar to vector but additionally contains the dimension attribute. All attributes of an object can be checked with the `attributes`() function (dimension can be checked directly with the `dim`() function).


In [98]:
# Get the number of rows in the matrix
dim(info2)

[1] 4 4

- This indicates that info2 has 4 rows and 4 columns.

- You can also use `dim()` to set the dimensions of a matrix or array. For example, you can reshape a vector into a matrix:

In [100]:
# Change the dimensions of the matrix to 8 rows and 2 columns
dim(info2) <- c(8, 2)
print(info2)

     [,1] [,2]
[1,]    1    3
[2,]    4    6
[3,]    7    9
[4,]   10   12
[5,]    2   12
[6,]    5   24
[7,]    8   35
[8,]   11   48


In [102]:
# Change the dimensions of the matrix to 2 rows and 8 columns
dim(info2)

[1] 8 2

### Transposition in R Matrix
___

The transpose in R for a matrix is achieved using the `t()` function. It swaps the rows and columns of the matrix, creating a new matrix with the original elements rearranged.

Here's a breakdown of how it works:

Function:
```R
t(matrix): Takes a matrix as input and returns its transpose.
```
Effect: Rows become columns, and columns become rows.



In [104]:
# transpose the matrix
t(info2)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    4    7    10    2    5    8   11  
[2,] 3    6    9    12   12   24   35   48

In [105]:
# Original matrix
my_matrix <- matrix(1:9, nrow = 3, ncol = 3)
print(my_matrix)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [106]:
# Transposed matrix
transposed_matrix <- t(my_matrix)
print(transposed_matrix)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


### R Matrix Operations
___

There are several operations that we can perform on the R matrices to get desired results:

In order to perform addition on matrices in R, we first create two matrices ‘mat1’ and ‘mat2’ with four rows and four columns as follows:

In [109]:
# Original matrix
mat1 <- matrix(data = 1:8, nrow = 4, ncol = 4) #Creating our first matrix mat1 
mat2 <- matrix(data = 1:16, nrow = 4, ncol = 4) #Creating our second matrix mat2
print(mat1)
print(mat2)

     [,1] [,2] [,3] [,4]
[1,]    1    5    1    5
[2,]    2    6    2    6
[3,]    3    7    3    7
[4,]    4    8    4    8
     [,1] [,2] [,3] [,4]
[1,]    1    5    9   13
[2,]    2    6   10   14
[3,]    3    7   11   15
[4,]    4    8   12   16


In [111]:
# Adding two matrices
result <- mat1 + mat2
print(result)


     [,1] [,2] [,3] [,4]
[1,]    2   10   10   18
[2,]    4   12   12   20
[3,]    6   14   14   22
[4,]    8   16   16   24


In [112]:
# Subtracting two matrices
result <- mat1 - mat2
print(result)

     [,1] [,2] [,3] [,4]
[1,]    0    0   -8   -8
[2,]    0    0   -8   -8
[3,]    0    0   -8   -8
[4,]    0    0   -8   -8


In [113]:
# Multiplying two matrices
result <- mat1 * mat2
print(result)

     [,1] [,2] [,3] [,4]
[1,]    1   25    9   65
[2,]    4   36   20   84
[3,]    9   49   33  105
[4,]   16   64   48  128


In [115]:
# multiplying matrics with constant
result <- mat1 * 2
print(result)

     [,1] [,2] [,3] [,4]
[1,]    2   10    2   10
[2,]    4   12    4   12
[3,]    6   14    6   14
[4,]    8   16    8   16


In [116]:
# Dividing two matrices
result <- mat1 / mat2
print(result)

     [,1] [,2]      [,3]      [,4]
[1,]    1    1 0.1111111 0.3846154
[2,]    1    1 0.2000000 0.4285714
[3,]    1    1 0.2727273 0.4666667
[4,]    1    1 0.3333333 0.5000000


### Applications of R Matrices
___

- In geology, matrices are used for taking surveys and also used for plotting graphs, statistics, and studies in different fields.
- To represent the real world data is like traits of people’s population. They are the best representation method for plotting common survey things.
- In robotics and automation, matrices are the best elements for the robot movements.
- Matrices are used in calculating the gross domestic products in Economics. Therefore, it helps in calculating the efficiency of goods and products.
- In computer-based application, matrices play a vital role in the projection of three-dimensional image into a two-dimensional screen, creating a realistic seeming motion.
- In physical related applications, matrices can be applied in the study of an electrical circuit.
