In [1]:
n <- rbind(c(1, 2, 3), c(4, 5, 6))
print(n)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6


In [2]:
# We can add name to the rows and columns of the matrix
A<-matrix(c(1,2,3,4,5,6,7,8,9), nrow = 3, ncol = 3,  dimnames = list(c("x", "y", "z"),  c("A", "B", "C"))) # nolint
print(A)
print(attributes(A))

print(colnames(A))

  A B C
x 1 4 7
y 2 5 8
z 3 6 9
$dim
[1] 3 3

$dimnames
$dimnames[[1]]
[1] "x" "y" "z"

$dimnames[[2]]
[1] "A" "B" "C"


[1] "A" "B" "C"


In [9]:

variable <- c(1, 2, 3, 4, 5, 56)
print(variable)
print(typeof(variable))


[1]  1  2  3  4  5 56
[1] "double"


In [4]:
detail <-matrix (c (1, 2, 3, 4, 6, 7, 7, 7, 7, 7), nrow = 5, ncol = 2, dimnames = list(c("x", "y", "z", "a", "b"),  c("A", "B"))) # nolint
print(detail)
attributes(detail)
colnames(detail)
rownames(detail)B

ERROR: Error in parse(text = x, srcfile = src): <text>:5:17: unexpected symbol
4: colnames(detail)
5: rownames(detail)B
                   ^


In [5]:
n <- rbind(c(1, 2, 3), c(4, 5, 6))
print(n)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6


In [8]:
m <- matrix(c(1, 2, 3, 4, 6, 7, 8, 9, 0),
nrow = 3,ncol = 3,
dimnames = list(c("xLagos", "yAbuja", "zEnugu"),  c("A", "B", "C"))) # nolint
print(m)
attributes(m)

       A B C
xLagos 1 4 8
yAbuja 2 6 9
zEnugu 3 7 0


$dim
[1] 3 3

$dimnames
$dimnames[[1]]
[1] "xLagos" "yAbuja" "zEnugu"

$dimnames[[2]]
[1] "A" "B" "C"

In [9]:
B <- cbind(c(1, 2, 3), c(4, 5, 6))
print(B)

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6


In [17]:
B <- rbind(c(1, 2, 3), c(4, 5, 6))

print(B[1,])


[1] 1 2 3


In [11]:
print(B)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6


In [30]:
employee_data <- data.frame(
  emp_id = c(1, 2, 3, 4, 5),
  emp_name = c("Rick", "Dan", "Michelle", "Ryan", "Gary"),
  salary = c(623.3, 515.2, 611.0, 729.0, 843.25))

print(employee_data)


  emp_id emp_name salary
1      1     Rick 623.30
2      2      Dan 515.20
3      3 Michelle 611.00
4      4     Ryan 729.00
5      5     Gary 843.25


In [34]:
employee_data <- data.frame(
  emp_id = c(1, 2, 3, 4, 5),
  emp_name = c("Rick", "Dan", "Michelle", "Ryan", "Gary"),
  salary = c(623.3, 515.2, 611.0, 729.0, 843.25)
)

print(employee_data)

  emp_id emp_name salary
1      1     Rick 623.30
2      2      Dan 515.20
3      3 Michelle 611.00
4      4     Ryan 729.00
5      5     Gary 843.25


In [35]:
typeof(employee_data)
class(employee_data)

[1] "list"

[1] "data.frame"

In [37]:
ncol(employee_data)
rownames(employee_data)

[1] 3

[1] "1" "2" "3" "4" "5"

In [38]:
str(employee_data)

'data.frame':	5 obs. of  3 variables:
 $ emp_id  : num  1 2 3 4 5
 $ emp_name: chr  "Rick" "Dan" "Michelle" "Ryan" ...
 $ salary  : num  623 515 611 729 843


In [39]:
employee_data["emp_name"]

emp_name
1 Rick    
2 Dan     
3 Michelle
4 Ryan    
5 Gary

In [57]:
employee_data$emp_name

[1] "John"     "Dan"      "Michelle" "Ryan"     "Gary"     "Teslim"   "Teslim"

In [58]:
employee_data[[2]]

[1] "John"     "Dan"      "Michelle" "Ryan"     "Gary"     "Teslim"   "Teslim"

In [59]:
employee_data[1, 1] <- "John"
print(employee_data)

  emp_id emp_name   salary
1   John     John   623.30
2      2      Dan   515.20
3      3 Michelle   611.00
4      4     Ryan   729.00
5      5     Gary   843.25
6      6   Teslim 10200.00
7      6   Teslim 10200.00


In [60]:
clean_Ace <- rbind(employee_data, list(6, "Teslim", 10200))
print(Clean_Ace)

  emp_id emp_name   salary
1   John     John   623.30
2      2      Dan   515.20
3      3 Michelle   611.00
4      4     Ryan   729.00
5      5     Gary   843.25
6      6   Teslim 10200.00
7      6   Teslim 10200.00
8      6   Teslim 10200.00


In [61]:
Clean_Ace_2 <- cbind(clean_Ace, state = c("Lagos", "Abuja", "Enugu", "Lagos", "Abuja", "Enugu", "Ab", "hshs"))
print(Clean_Ace_2)

  emp_id emp_name   salary state
1   John     John   623.30 Lagos
2      2      Dan   515.20 Abuja
3      3 Michelle   611.00 Enugu
4      4     Ryan   729.00 Lagos
5      5     Gary   843.25 Abuja
6      6   Teslim 10200.00 Enugu
7      6   Teslim 10200.00    Ab
8      6   Teslim 10200.00  hshs


In [63]:
employee_data$salary <- NULL
print(employee_data)

  emp_id emp_name
1   John     John
2      2      Dan
3      3 Michelle
4      4     Ryan
5      5     Gary
6      6   Teslim
7      6   Teslim


In [65]:

print(emp_data)
# Create the data frame.
emp_data <- data.frame(
  emp_id = c(1:5),
  emp_name = c("Rick", "Dan", "Michelle", "Ryan", "Gary"),
  salary = c(623.3, 515.2, 611.0, 729.0, 843.25),
  start_date = as.Date(c("2012-01-01", "2013-09-23", "2014-11-15", "2014-05-11",
                         "2015-03-27")),
  stringsAsFactors = FALSE
)
# Print the data frame.
print(emp.data)

  emp_id emp_name salary start_date
1      1     Rick 623.30 2012-01-01
2      2      Dan 515.20 2013-09-23
3      3 Michelle 611.00 2014-11-15
4      4     Ryan 729.00 2014-05-11
5      5     Gary 843.25 2015-03-27
